name = "haqiba-admin"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "haqiba-db"
database_id = "4130be70-3380-4fc6-9139-b5103aaf0c54"

[[kv_namespaces]]
binding = "KV"
id = "b1d08cf9f18443a8b1f61eb21aa69078"

[[r2_buckets]]
binding = "FILES"
bucket_name = "haqiba-files"
